### ISSUE TITLE
writeFlameGraph throws SyntaxError

### ISSUE THREAD

**Issue by pbadenski** [humu/heapprof#23]
Based on example from the documentation:
```
>>> r.writeFlameGraph('flame-3800.txt', 3800)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/heapprof/reader.py", line 403, in writeFlameGraph
    self.asFlameGraph(when, output)
AttributeError: 'Reader' object has no attribute 'asFlameGraph'
```

From what I understand this should be `self.flameGraphAt(when, output)`

**Comment by zunger-humu** [comment]
Oops, good catch. Fixing now.

**Comment by zunger-humu** [comment]
(Whoops, forgot to close the issue in March when the fix was pushed)
